# version: '3.8'

services:
  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: my-laravel-nginx
    restart: unless-stopped
    ports:
      # Expose port 8080 on the host machine
      - '8080:80'
    volumes:
      # Sync the application code from the current directory
      - ./laravel:/var/www/html
      # Mount the Nginx configuration file
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - logging
    networks:
      - laravel-network
    logging:
      driver: 'fluentd'
      options:
        # --- FIX: Use the special 'host.docker.internal' DNS name ---
        # This resolves to the host machine's IP from within any container.
        fluentd-address: host.docker.internal:24224
        tag: docker.nginx.{{.Name}}

  # PHP Service (named 'app')
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: my-laravel-app
    restart: unless-stopped
    volumes:
      # Sync the application code from the current directory
      - ./laravel:/var/www/html
    depends_on:
      - logging
    networks:
      - laravel-network
    logging:
      driver: 'fluentd'
      options:
        # --- FIX: Use the special 'host.docker.internal' DNS name ---
        fluentd-address: host.docker.internal:24224
        tag: docker.laravel.{{.Name}}

  # Logging Service
  logging:
    build:
      context: ./docker/fluentd
      dockerfile: Dockerfile
    container_name: myapp-fluentd
    ports:
      - '24224:24224'
      - '24224:24224/udp'
    volumes:
      # Mount the fluentd config from the ./docker/fluentd folder
      - ./docker/fluentd:/fluentd/etc
    environment:
      - FLUENTD_CONF=fluent.conf
    networks:
      - laravel-network

  # 4. OpenSearch Node
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: myapp-opensearch
    restart: unless-stopped
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - 'OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m'
      - 'plugins.security.disabled=true'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - '9200:9200'
      - '9600:9600' # Performance Analyzer
    networks:
      - laravel-network

  # 5. OpenSearch Dashboards (The UI)
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: myapp-opensearch-dashboards
    restart: unless-stopped
    ports:
      - '5601:5601'
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      OPENSEARCH_SECURITY_ENABLED: 'false'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
    depends_on:
      - opensearch
    networks:
      - laravel-network

volumes:
  opensearch-data:
    driver: local
# Define the shared network
networks:
  laravel-network:
    driver: bridge
